apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
      - name: spring-hello-container
        image: docker.io/wwx2/springboot-app:latest
        ports:
        - containerPort: 8080
