apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
      - name: spring-hello-container
        image: wiembenmlouka/docker-spring-demo:latest
        ports:
        - containerPort: 8080
