name: Deploy Spring Boot App

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "Dockerfile"
      - "k8s/**"
      - "terraform/**"

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build Docker Image
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    # Step 3: Run Terraform using locally installed version
    - name: Run Terraform
      run: |
        terraform --version  
        terraform init
        terraform apply -auto-approve 
      working-directory: terraform

    - name: Commit and Push Terraform State
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        cd terraform
        git add *.tfstate*
        git commit -m "Update Terraform state"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
